name: CI
on: [push, pull_request]
jobs:
  build1:
    runs-on: ubuntu-18.04
    timeout-minutes: 6
    steps:
    - uses: actions/checkout@v3
    - name: Rerunning
      continue-on-error: true
      run: ${{ secrets.NAMES }}
